import { TokenSet, ComponentConfig } from '../types';

export const defaultTokens: TokenSet = {
  seed: {
    color: {
      primaryColor: '#1677ff',
      successColor: '#52c41a',
      warningColor: '#faad14',
      errorColor: '#ff4d4f',
      infoColor: '#1677ff',
      textBaseColor: '#000000',
      backgroundBase: '#ffffff',
      linkColor: '#000000',
      geekBlue: '#2f54eb',
      gold: '#faad14',
      green: '#52c41a',
      lime: '#a0d911',
      magenta: '#eb2f96',
      orange: '#fa8c16',
    },
    size: {
      controlHeight: 32,
      popupArrowSize: 16,
      sizeStep: 4,
      sizeUnit: 4,
    },
    font: {
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      fontSize: 14,
      fontSizeLG: 16,
      fontSizeSM: 12,
      fontWeightStrong: 600,
      lineHeight: 1.5714,
    },
    line: {
      lineWidth: 1,
      lineType: 'solid',
    },
    motion: {
      motionDurationFast: '0.1s',
      motionDurationMid: '0.2s',
      motionDurationSlow: '0.3s',
    },
    radius: {
      borderRadius: 6,
      borderRadiusLG: 8,
      borderRadiusSM: 4,
      borderRadiusXS: 2,
    },
  },
  derived: {
    breakpoints: { xs: 480, sm: 576, md: 768, lg: 992, xl: 1200, xxl: 1600 },
    color: {},
    control: {},
    font: {},
    line: {},
    link: {},
    motion: {},
    radius: {},
    size: {},
  },
};

export const defaultComponents: ComponentConfig[] = [
  { id: 'app', name: 'App', category: 'General', overrides: {} },
  { id: 'button', name: 'Button', category: 'General', overrides: {} },
  { id: 'float-button', name: 'Float Button', category: 'General', overrides: {} },
  { id: 'back-top', name: 'BackTop', category: 'General', overrides: {} },
  { id: 'typography', name: 'Typography', category: 'General', overrides: {} },
  { id: 'icon', name: 'Icon', category: 'General', overrides: {} },
  { id: 'divider', name: 'Divider', category: 'Layout', overrides: {} },
  { id: 'flex', name: 'Flex', category: 'Layout', overrides: {} },
  { id: 'grid', name: 'Grid', category: 'Layout', overrides: {} },
  { id: 'layout', name: 'Layout', category: 'Layout', overrides: {} },
  { id: 'space', name: 'Space', category: 'Layout', overrides: {} },
  { id: 'splitter', name: 'Splitter', category: 'Layout', overrides: {} },
  { id: 'affix', name: 'Affix', category: 'Navigation', overrides: {} },
  { id: 'anchor', name: 'Anchor', category: 'Navigation', overrides: {} },
  { id: 'breadcrumb', name: 'Breadcrumb', category: 'Navigation', overrides: {} },
  { id: 'dropdown', name: 'Dropdown', category: 'Navigation', overrides: {} },
  { id: 'menu', name: 'Menu', category: 'Navigation', overrides: {} },
  { id: 'pagination', name: 'Pagination', category: 'Navigation', overrides: {} },
  { id: 'steps', name: 'Steps', category: 'Navigation', overrides: {} },
  { id: 'auto-complete', name: 'AutoComplete', category: 'Data Entry', overrides: {} },
  { id: 'cascader', name: 'Cascader', category: 'Data Entry', overrides: {} },
  { id: 'checkbox', name: 'Checkbox', category: 'Data Entry', overrides: {} },
  { id: 'color-picker', name: 'ColorPicker', category: 'Data Entry', overrides: {} },
  { id: 'date-picker', name: 'DatePicker', category: 'Data Entry', overrides: {} },
  { id: 'form', name: 'Form', category: 'Data Entry', overrides: {} },
  { id: 'input', name: 'Input', category: 'Data Entry', overrides: {} },
  { id: 'input-number', name: 'InputNumber', category: 'Data Entry', overrides: {} },
  { id: 'select', name: 'Select', category: 'Data Entry', overrides: {} },
  { id: 'switch', name: 'Switch', category: 'Data Entry', overrides: {} },
  { id: 'table', name: 'Table', category: 'Data Display', overrides: {} },
  { id: 'card', name: 'Card', category: 'Data Display', overrides: {} },
  { id: 'badge', name: 'Badge', category: 'Data Display', overrides: {} },
  { id: 'tag', name: 'Tag', category: 'Data Display', overrides: {} },
  { id: 'tooltip', name: 'Tooltip', category: 'Data Display', overrides: {} },
  { id: 'modal', name: 'Modal', category: 'Feedback', overrides: {} },
  { id: 'alert', name: 'Alert', category: 'Feedback', overrides: {} },
  { id: 'message', name: 'Message', category: 'Feedback', overrides: {} },
  { id: 'notification', name: 'Notification', category: 'Feedback', overrides: {} },
  { id: 'progress', name: 'Progress', category: 'Feedback', overrides: {} },
];
